### ISSUE TITLE
Add Docker Support for Blazor

### ISSUE THREAD

**Issue by mansabbloch** [WITPASS/WebApp#12]
Blazor is client side technology asp.net web server can't be used. We need to add nginx to server compiled files as static resources.

**Comment by mansabbloch** [comment]
Done

**Comment by KamranAzeem** [comment]
Please use this : https://github.com/WITPASS/Witpass-Infrastructure/blob/master/docs/how-to-create-custom-labels-for-github-issues.md to have a consistency in our labeling system :)
